export enum NotificacaoTipo {
  SOCIAL = 'SOCIAL',
  MOVIMENTO = 'MOVIMENTO',
  AREA_PERIGOSA = 'AREA_PERIGOSA',
  ROUBO = 'ROUBO',
  TRANSACAO_SOLICITADA = 'TRANSACAO_SOLICITADA',
  TRANSACAO_AGUARDANDO_ACEITE_COMPRADOR = 'TRANSACAO_AGUARDANDO_ACEITE_COMPRADOR',
  TRANSACAO_AGUARDANDO_CONFIRMACAO_VENDEDOR = 'TRANSACAO_AGUARDANDO_CONFIRMACAO_VENDEDOR',
  TRANSACAO_CANCELADA_COMPRADOR = 'TRANSACAO_CANCELADA_COMPRADOR',
  TRANSACAO_CANCELADA_VENDEDOR = 'TRANSACAO_CANCELADA_VENDEDOR',
  TRANSACAO_CONCLUIDA = 'TRANSACAO_CONCLUIDA',
  AMIZADE = 'AMIZADE',
}
