export enum TransacaoStatus {
  CANCELADA = 'CANCELADA',
  CANCELADA_PELO_VENDEDOR = 'CANCELADA_PELO_VENDEDOR',
  CANCELADA_PELO_COMPRADOR = 'CANCELADA_PELO_COMPRADOR ',
  AGUARDANDO_ACEITE_COMPRADOR = 'AGUARDANDO_ACEITE_COMPRADOR',
  AGUARDANDO_CONFIRMACAO_VENDEDOR = 'AGUARDANDO_CONFIRMACAO_VENDEDOR',
  CONCLUIDA = 'CONCLUIDA',
}
